services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    image: expense-tracker-api-dev
    container_name: expense-tracker-api-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
